### PR TITLE
first version of reprex and addins

### PR DESCRIPTION
**Pull request by DavZim**
This is a first version of the reprex/addins feature request (#27).

The code in the PR should work but is not finished, instead, this PR has the goal to be a basis for discussion.
  
This code adds two functions which act like a reprex, create a reprex and carbonify(?) the output of the reprex either opening the browser or downloading the file directly.

Additionally, RStudio addins are added to make it easier to use and potentially bind it to keyboard shortcuts.

Contrary to the issue, this uses reprex, therefore selected code is not used, instead code from the clipboard is used (which is imo more user friendly).

Let me know if this makes it more clear and if this is something that could be included (if more tests are added etc).

Thanks

### CODE REVIEW

**Comment by yonicd** [comment]
thanks for the PR. will take a closer look over the weekend.

**Comment by DavZim** [comment]
Any opinions on this?

**Comment by yonicd** [comment]
Working on the other PR at the moment. 

This looks good. 

Once the new version is up I'll weave this PR into it.

Thanks!

**Comment by yonicd** [comment]
Had a chance to give it a spin.

Overall it looks good. A few things that would need to be updated

- [ ] use rstudioapi to capture highlighted text from the editor when running as addin
- [ ] if any device output is generated (png) capture it (or its url) and add it as an image object to the parent carbon object

**Comment by DavZim** [comment]
I tend to agree that the addin should not only work from clipboard but also from selected code. As we use `...` to pass all arguments to reprex, I am not sure how we can achieve this. One way would be to limit the addin to use _only_ selected code and do not work with code on the clipboard.

Ad 2. How can we combine the parent carbon object with the imgur reprex image? This should be optional as for example in my case I rarely want to have the image in the carbon as well

**Comment by yonicd** [comment]
1. That is what i meant. to have addin only work on highlighted text. 
- addins need to be input type specific, ie you can have two addins, one for clipboard one for editor.

2. Carbon objects can also share the content (eg tweets). it would make most sense to keep the side effects reprex generates to attached to the content that carbon is sharing.

**Pull request merged**
